//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyOfShikshanSankraman.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDatabaseEntities1 : DbContext
    {
        public NewDatabaseEntities1()
            : base("name=NewDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NewWriter_tbl> NewWriter_tbl { get; set; }
        public virtual DbSet<NewChitrakar_tbl> NewChitrakar_tbl { get; set; }
        public virtual DbSet<School_tbl> School_tbl { get; set; }
        public virtual DbSet<Mahavidyalaya_tbl> Mahavidyalaya_tbl { get; set; }
        public virtual DbSet<NewVarganidar_tbl> NewVarganidar_tbl { get; set; }
        public virtual DbSet<Pratikriya_tbl> Pratikriya_tbl { get; set; }
        public virtual DbSet<Contact_tbl> Contact_tbl { get; set; }
        public virtual DbSet<Admin_tbl1> Admin_tbl1 { get; set; }
        public virtual DbSet<Tbl_payment> Tbl_payment { get; set; }
        public virtual DbSet<NewKaryalay_tbl> NewKaryalay_tbl { get; set; }
        public virtual DbSet<Tbl_Mandal> Tbl_Mandal { get; set; }
        public virtual DbSet<Registration_tbl> Registration_tbl { get; set; }
    }
}
