//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyOfShikshanSankraman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pratikriya_tbl
    {
        public int id { get; set; }
        public string FullName { get; set; }
        public string MobileNo { get; set; }
        public string Education { get; set; }
        public string Varsh { get; set; }
        public string Mahine { get; set; }
        public string Pratikriya { get; set; }
    }
}
