//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyOfShikshanSankraman.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Mandal
    {
        public int id { get; set; }
        public string ino { get; set; }
        public string year { get; set; }
        public string month { get; set; }
        public string address { get; set; }
    }
}
